### PR TITLE
astrobwt: fix build with gcc-4.8

### PR DESCRIPTION
**Pull request by bkuhls**
Fixes build error:

xmrig-6.17.0/src/crypto/astrobwt/sort_indices2.cpp:40:24: error: missing binary operator before token "("
 #if __has_cpp_attribute(unlikely)

found with the buildroot toolchain
arm-none-linux-gnueabi-gcc (Sourcery CodeBench Lite 2014.05-29) 4.8.3 20140320 (prerelease)

Inspired by
https://reviews.llvm.org/rG91c32fd8c8fa395971a028f7091273fa2c8f44e6

### CODE REVIEW

**Comment by Spudz76** [comment]
Didn't know such an antique compiler worked at all even for the rest of things.

**Comment by bkuhls** [comment]
It does:
```
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/buildroot/build/output/per-package/xmrig/host/bin/arm-none-linux-gnueabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/buildroot/build/output/per-package/xmrig/host/bin/arm-none-linux-gnueabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test VAES_SUPPORTED
-- Performing Test VAES_SUPPORTED - Failed
-- Use ARM_TARGET=7 (armv7l)
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found UV: /home/buildroot/build/output/per-package/xmrig/host/arm-buildroot-linux-gnueabi/sysroot/thumb2/usr/lib/libuv.so  
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - found
-- WITH_MSR=OFF
-- Found OpenSSL: /home/buildroot/build/output/per-package/xmrig/host/arm-buildroot-linux-gnueabi/sysroot/usr/lib/libcrypto.so (found version "1.1.1o")  
-- Configuring done
-- Generating done
```
```
$ file xmrig
xmrig: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.16, stripped
```

**Review by SChernykh — APPROVED** [review]

**Comment by Spudz76** [comment]
AstroBWT completely dropped now, so thanks but... now that file is deleted so there is nothing to patch.
