### ISSUE TITLE
Cant build on FreeBSD (xmrirg v2.9.2)

### ISSUE THREAD

**Issue by pboguk** [xmrig/xmrig#909]
Hello,

11.1-RELEASE FreeBSD(different HW in all cases)
Always get 
[ 98%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/Asm.cpp.o
[100%] Linking CXX executable xmrig
/usr/bin/ld: undefined reference to symbol `pthread_condattr_init@@FBSD_1.0' (try adding -lthr)
//lib/libthr.so.3: could not read symbols: Bad value
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

On FreeBSD 10.3  I get:

CMakeFiles/xmrig.dir/src/common/Platform_unix.cpp.o: In function `Platform::setThreadAffinity(unsigned long)':
Platform_unix.cpp:(.text+0xe7): undefined reference to `pthread_setaffinity_np'
/usr/local/lib/libuv.a(libuv_la-thread.o): In function `uv_thread_create':
(.text+0x13): undefined reference to `pthread_create'

**Comment by pboguk** [comment]
Also, on 10.4-RELEASE I get 
[ 75%] Building CXX object CMakeFiles/xmrig.dir/src/Mem_unix.cpp.o
/usr/home/pboguk/xmrig/src/Mem_unix.cpp:105:5: error: use of undeclared identifier '__builtin___clear_cache'
    __builtin___clear_cache(reinterpret_cast<char*>(p), reinterpret_cast<char*>(p) + size);

**Comment by xmrig** [comment]
About pthread errors please add `pthread` https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L161 here, it should help, if not enough also add `rt` and `dl`.

About second error, what compiler version do you use?
Thank you.

**Comment by pboguk** [comment]
Changing to
    161         set(EXTRA_LIBS kvm pthread rt dl)

Did the thing. Now it builds as usual in both cases.

Thank you!

**Comment by pboguk** [comment]
Regarding

Also, on 10.4-RELEASE I get
[ 75%] Building CXX object CMakeFiles/xmrig.dir/src/Mem_unix.cpp.o
/usr/home/pboguk/xmrig/src/Mem_unix.cpp:105:5: error: use of undeclared identifier '__builtin___clear_cache'

I updated GCC and now it buids without error.

Thank you for great project!

**Comment by pboguk** [comment]
I've already built on 10x and 11x using advice from developer(see before in topic).
So 12.0, 11.2 shoud not have problems.

**Comment by xmrig** [comment]
Build restored in master branch, I checked on FreeBSD 10.3 with clang 3.4.1.
Thank you.
