### ISSUE TITLE
### How to static linking to glibc in xmrig

### ISSUE THREAD

**Issue by hyassine53** [xmrig/xmrig#185]
I'm trying to build xmrig  that can run on a RedHat 6 machine. So I need to build and static linking with some library that does not exist in RedHat machine. I found that I can use -static-libgcc or -static-libstdc++ to link with static version of standard library but I don't know how to do with glibc. How can I link to static library of glibc with CMake?
libc.so.6: version `GLIBC_2.17' not found make m crazy 
Sorry , i am not expert

**Comment by yyfong0918** [comment]
Why not build xmrig on that RH 6 machine?

**Comment by Algeroth123** [comment]
Mostly because it does not want to compile on rh6/centos6/oel6 at all
everytime throws an error, 
[ 17%] Building CXX object CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o
/root/xmrig/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/root/xmrig/src/api/ApiState.cpp:143:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/root/xmrig/src/api/ApiState.cpp:150:58: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^~~~~~~~~
/root/xmrig/src/api/ApiState.cpp:154:41: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^~~~~~~~~
CMakeFiles/xmrig.dir/build.make:86: recipe for target 'CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig.dir/all' failed
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2


either on gcc6, or gcc7


compiling on rh7.... works well

**Comment by yyfong0918** [comment]
For your reference, I can compile on centos 6.9, devtoolset-6 (gcc 6.3.1), and libuv 1.15-dev.
I disabled http support since I do not need it.

**Comment by Algeroth123** [comment]
thanks, compiled properly now on centos6, had to compile libuv 1.16.1 by myself.

**Comment by yyfong0918** [comment]
OK, and have a nice day!
