### PR TITLE
fix build error on gcc 4.8.5

### PR DESCRIPTION
**Pull request by esrrhs**
when build on some old gcc version, such as 9.3.0, is will failed with
`
FileLogWriter.h:34:41: error: array used as initializer
`

### CODE REVIEW

**Comment by xmrig** [comment]
This is strange because code compiles with gcc 9.3.0 just fine, for example:

1. https://buildbot.xmrig.com/#/builders/14/builds/413
2. https://buildbot.xmrig.com/#/builders/15/builds/413

**Comment by esrrhs** [comment]
I got the version number wrong, it's actually gcc 4.8.5
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found HWLOC: /usr/lib64/libhwloc.so  
-- Found UV: /usr/lib64/libuv.a  
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - found
-- WITH_MSR=ON
-- argon2: detecting feature 'sse2'...
-- Performing Test FEATURE_sse2_NOFLAG
-- Performing Test FEATURE_sse2_NOFLAG - Success
-- argon2: feature 'sse2' detected!
-- argon2: detecting feature 'ssse3'...
-- Performing Test FEATURE_ssse3_NOFLAG
-- Performing Test FEATURE_ssse3_NOFLAG - Failed
-- Performing Test FEATURE_ssse3_FLAG
-- Performing Test FEATURE_ssse3_FLAG - Success
-- argon2: feature 'ssse3' detected!
-- argon2: detecting feature 'xop'...
-- Performing Test FEATURE_xop_NOFLAG
-- Performing Test FEATURE_xop_NOFLAG - Failed
-- Performing Test FEATURE_xop_FLAG
-- Performing Test FEATURE_xop_FLAG - Success
-- argon2: feature 'xop' detected!
-- argon2: detecting feature 'avx2'...
-- Performing Test FEATURE_avx2_NOFLAG
-- Performing Test FEATURE_avx2_NOFLAG - Failed
-- Performing Test FEATURE_avx2_FLAG
-- Performing Test FEATURE_avx2_FLAG - Success
-- argon2: feature 'avx2' detected!
-- argon2: detecting feature 'avx512f'...
-- Performing Test FEATURE_avx512f_NOFLAG
-- Performing Test FEATURE_avx512f_NOFLAG - Failed
-- Performing Test FEATURE_avx512f_FLAG
-- Performing Test FEATURE_avx512f_FLAG - Failed
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/project/xmrig/build
[root@iz2ze0tbgh62sv1mi6afgqz build]# mkae^C
[root@iz2ze0tbgh62sv1mi6afgqz build]# make 
Scanning dependencies of target argon2-xop
[  0%] Building C object src/3rdparty/argon2/CMakeFiles/argon2-xop.dir/arch/x86_64/lib/argon2-xop.c.o
Linking C static library libargon2-xop.a
[  0%] Built target argon2-xop
Scanning dependencies of target xmrig-asm
[  0%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/cn/asm/cn_main_loop.S.o
[  1%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/cn/asm/CryptonightR_template.S.o
Linking C static library libxmrig-asm.a
[  1%] Built target xmrig-asm
Scanning dependencies of target ethash
[  2%] Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o
[  2%] Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/keccakf800.c.o
Linking C static library libethash.a
[  2%] Built target ethash
Scanning dependencies of target argon2-avx512f
[  2%] Building C object src/3rdparty/argon2/CMakeFiles/argon2-avx512f.dir/arch/x86_64/lib/argon2-avx512f.c.o
Linking C static library libargon2-avx512f.a
[  2%] Built target argon2-avx512f
Scanning dependencies of target argon2-ssse3
[  3%] Building C object src/3rdparty/argon2/CMakeFiles/argon2-ssse3.dir/arch/x86_64/lib/argon2-ssse3.c.o
Linking C static library libargon2-ssse3.a
[  3%] Built target argon2-ssse3
Scanning dependencies of target argon2-sse2
[  3%] Building C object src/3rdparty/argon2/CMakeFiles/argon2-sse2.dir/arch/x86_64/lib/argon2-sse2.c.o
Linking C static library libargon2-sse2.a
[  3%] Built target argon2-sse2
Scanning dependencies of target argon2-avx2
[  4%] Building C object src/3rdparty/argon2/CMakeFiles/argon2-avx2.dir/arch/x86_64/lib/argon2-avx2.c.o
Linking C static library libargon2-avx2.a
[  4%] Built target argon2-avx2
Scanning dependencies of target argon2
[  4%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
[  4%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/core.c.o
[  5%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/encoding.c.o
[  5%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/genkat.c.o
[  5%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/impl-select.c.o
[  6%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/blake2/blake2.c.o
[  6%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/arch/x86_64/lib/argon2-arch.c.o
Linking C static library libargon2.a
[  6%] Built target argon2
Scanning dependencies of target xmrig
[  6%] Building CXX object CMakeFiles/xmrig.dir/src/3rdparty/fmt/format.cc.o
[  7%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/CpuLaunchData.cpp.o
 [  7%] Building CXX object CMakeFiles/xmrig.dir/src/backend/opencl/kernels/rx/HashAesKernel.cpp.o
[  8%] Building CXX object CMakeFiles/xmrig.dir/src/base/crypto/Algorithm.cpp.o
[  8%] Building CXX object CMakeFiles/xmrig.dir/src/base/crypto/Coin.cpp.o
[  8%] Building CXX object CMakeFiles/xmrig.dir/src/base/crypto/keccak.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig.dir/src/base/crypto/sha3.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/Async.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/Console.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/Env.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/json/Json.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/json/JsonChain.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/json/JsonRequest.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/log/backends/ConsoleLog.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/log/backends/FileLog.cpp.o
In file included from /home/project/xmrig/src/base/io/log/backends/FileLog.h:24:0,
                 from /home/project/xmrig/src/base/io/log/backends/FileLog.cpp:21:
/home/project/xmrig/src/base/io/log/FileLogWriter.h: In constructor ‘xmrig::FileLogWriter::FileLogWriter(const char*)’:
/home/project/xmrig/src/base/io/log/FileLogWriter.h:34:41: error: array used as initializer
     FileLogWriter(const char *fileName) { open(fileName); }
                                         ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-class-memaccess" [enabled by default]
make[2]: *** [CMakeFiles/xmrig.dir/src/base/io/log/backends/FileLog.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2
```
