### ISSUE TITLE
fatal error: uv.h: No such file or directory

### ISSUE THREAD

**Issue by LinProg** [xmrig/xmrig#571]
Ok, lets start off with BE CLEAR AND SPECIFIC because multiple people have this problem and nobody is giving a COMPLETE answer. Just "you need libuv and we have prebuilt version". Ok, well I've tried the following and still same problem so how about a step by step on how to install libuv.

Installed via these command lines:
`sudo apt-get install libuv1`
`sudo apt-get install libuv-dev`

Both say installed, so then I try:
`x86_64-w64-mingw32-g++ xmrig.cpp -o xmrig.exe`

Which still gives me the error:

`In file included from xmrig.cpp:24:0:
App.h:28:16: fatal error: uv.h: No such file or directory
compilation terminated.`

So I tried copying the uv.h file from xmrig-debs-3.0/x64/include/ and pasting it in my xmrig-master/src/ directory and the problem still persists. What am I supposed to do with the files in xmrig-debs-3.0 that will make it work? Because you dont give any instruction whatsoever beyond downloading the files making it impossible for people trying to compile on their own. And instead of telling me vaguely "install libuv" give STEP-BY-STEP instructions cause as I've described I tried doing that in multiple ways and nothing worked. I am using Ubuntu 16.04 and I'm trying to compile for Windows. I've only written programs in Java and other web based languages like PHP so if theres something else I gotta configure for the C++ compiler that'd be pretty useful information.

**Comment by LinProg** [comment]
So how am I supposed to build it straight from the source? I've added command line arguments so when I double click the executable I dont have to enter my address or the mining pool as I hard coded them in xmrig.cpp

The following command appears to only build from the original source and from the default program download location. I have a xmrig-master directory in my home folder. How would I compile by opening this directory in the terminal?

```
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake ..
make
```

**Comment by xmrig** [comment]
change `cd xmrig` to `cd ~/xmrig-master`.
