### PR TITLE
+15% boost on CryptoNight algo with non-AES CPU

### PR DESCRIPTION
**Pull request by Foudge**
Performance boost validated on Core 2 Quad processor under Windows 10.
But it's Windows/MS Visual C++ specific.

### CODE REVIEW

**Comment by sergneo** [comment]
Confirm the performance increase by 7.5-8% CPU on a Core2Duo E8500, Windows 7 Prof x64 sp1.
All x32 x64 builds of GCC increasing no. Only build VC2017 increases the speed. Old version 45,6 H/s, the new version of 49,3 H/s

**Comment by Foudge** [comment]
Can you confirm perf boost with GCC with this code ?
const uint32_t x0 = ((uint32_t*)&in)[0];
const uint32_t x1 = ((uint32_t*)&in)[1];
const uint32_t x2 = ((uint32_t*)&in)[2];
const uint32_t x3 = ((uint32_t*)&in)[3];

**Comment by sergneo** [comment]
I'm not a C programmer , I don't know where to insert this code.

**Comment by Foudge** [comment]
In the file src/crypto/soft_aes.h
Line 100 to 104, replace :
const uint32_t x0 = _mm_cvtsi128_si32(in);
const uint32_t x1 = _mm_cvtsi128_si32(_mm_shuffle_epi32(in, 0x55));
const uint32_t x2 = _mm_cvtsi128_si32(_mm_shuffle_epi32(in, 0xAA));
const uint32_t x3 = _mm_cvtsi128_si32(_mm_shuffle_epi32(in, 0xFF));
With this :
const uint32_t x0 = ((uint32_t*)&in)[0];
const uint32_t x1 = ((uint32_t*)&in)[1];
const uint32_t x2 = ((uint32_t*)&in)[2];
const uint32_t x3 = ((uint32_t*)&in)[3];

GCC builds fail or not? Same performance increase?

**Comment by sergneo** [comment]
Yes, I thought so immediately, I tried that, the compiler swore, but worked. The increase seems to have been but very small, somewhere +1-2 H/s

**Comment by rtau** [comment]
Just to share some information on the warning, which I think using union may help.

http://cellperformance.beyond3d.com/articles/2006/06/understanding-strict-aliasing.html

**Comment by Foudge** [comment]
I installed MSYS2 and do some tests with MSVC and GCC (7.3.0), 2 thread on a C2Q@3.2GHz.
before
MSVC: 28.7 H/s
GCC: 27.5 H/s
after
MSVC (using field): 33.4 H/s (+16%)
MSVC (using cast): 33.3 H/s (+16%)
GCC (using cast): 28.2 H/s (+2.5%)

So, with GCC, there is an aliasing warning and no significant perf increase.

**Comment by Foudge** [comment]
Someone can try this : https://github.com/Foudge/xmrig/commit/9a28ad590ca6137bf5e19ba477e3f379527bbd73
It's slightly better and get a good perf increase with GCC too!

If confirmed, I will do a new pull request.

**Comment by sergneo** [comment]
Great, indeed, the new c code GCC 7.3.0 improves performance. 
E8500 - 45,6 -> 52 H/s (~15%)
E8400 - 44 -> 49 H/s (~11%)
Q9400 - 75 -> 85 H/s (~13%)
------------------------------
Win 7 x64 Pro sp1

**Comment by sergneo** [comment]
Great, indeed, the new c code GCC 7.3.0 improves performance. 
E8500 - 45,6 -> 52 H/s (~15%)
E8400 - 44 -> 49 H/s (~11%)
Q9400 - 75 -> 85 H/s (~13%)
------------------------------
Win 7 x64 Pro sp1

**Comment by sergneo** [comment]
> Great, indeed, the new c code GCC 7.3.0 improves performance. 
> E8500 - 45,6 -> 52 H/s (~15%)
> E8400 - 44 -> 49 H/s (~11%)
> Q9400 - 75 -> 85 H/s (~13%)
> ------------------------------
> Win 7 x64 Pro sp1
>

**Comment by sergneo** [comment]
Great, indeed, the new c code GCC 7.3.0 improves performance.
E8500 - 45,6 -> 52 H/s (~14%)
E8400 - 44 -> 49 H/s (~11%)
Q9400 - 75 -> 85 m/s (~13%)
------------------------------
Win7 x64 Pro sp1

**Comment by Mila432** [comment]
even have some improvement on unix
original gcc 7.3.0
[2018-01-28 07:50:40] speed 2.5s/60s/15m 221.8 223.1 n/a H/s max: 224.1 H/s
with your patch
[2018-01-28 07:53:23] speed 2.5s/60s/15m 229.3 223.8 n/a H/s max: 229.6 H/s

**Comment by sergneo** [comment]
This improvement for processors without AES, you have any?

**Comment by Mila432** [comment]
@sergneo not sure running in a vmware on i7 7700k

**Comment by Foudge** [comment]
In theory, there should be no performance gain with an AES CPU like yours. XMRig show you CPU capabilities at the beginning.
But you can simulate lack of AES by modifiying the file config.json : put 3 to "av" parameter, and compare original and patched.

**Comment by lisergey** [comment]
didnot compile with CLANG under FreeBSD 11.1-RELEASE-p4

[ 34%] Building CXX object CMakeFiles/xmrig.dir/src/net/Client.cpp.o
/home/test/work/Foudge.xmrig/src/net/Client.cpp:535:42: error: use of undeclared identifier 'ULONG'
    buf->len  = client->m_recvBuf.len - (ULONG)client->m_recvBufPos;
                                         ^
1 error generated.
*** Error code 1

same machine, original xmrig does compile well

**Comment by sergneo** [comment]
Yes change the config:
"av": 3, // algorithm variation, 0 is auto select
upd:
I tested the speed on WinXP Pro sp3 32 bit on a E8400.
Old 34.7 H/s - new 35.7 add +1H/s

**Comment by lisergey** [comment]
GCC-7.30 didn't compile either 

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/local/bin/gcc7
-- Check for working C compiler: /usr/local/bin/gcc7 -- works
<skip>
-- Check for working CXX compiler: /usr/local/bin/g++7
-- Check for working CXX compiler: /usr/local/bin/g++7 -- works

[ 34%] Building CXX object CMakeFiles/xmrig.dir/src/net/Client.cpp.o
/home/test/work/Foudge.xmrig/src/net/Client.cpp: In static member function 'static void Client::onAllocBuffer(uv_handle_t*, size_t, uv_buf_t*)':
/home/test/work/Foudge.xmrig/src/net/Client.cpp:535:42: error: 'ULONG' was not declared in this scope
     buf->len  = client->m_recvBuf.len - (ULONG)client->m_recvBufPos;
                                          ^~~~~
*** Error code 1

**Comment by Foudge** [comment]
It's due to a previous commit to remove warning compilation under MSVC.
If you replace ULONG by unsigned long I think it will be ok. Can you confirm it ?
Do code compatible with multiple compiler and multiple OS is not simple, especially when we have only 1 of them :)

**Comment by sergneo** [comment]
mingw64

**Comment by lisergey** [comment]
@Foudge, thanks, with that replace gcc7-30 compiled.
would test its speed on several non-AES CPUs

**Comment by Mila432** [comment]
looks like i got 2,5 kh/s bonus on 400 unix miner

**Comment by lisergey** [comment]
original xmrig from FreeBSD ports
speed 2.5s/60s/15m 152.4 151.4 151.5 H/s max: 160.6 H/s
 
@Foudge xmrig
speed 2.5s/60s/15m 145.7 144.8 143.8 H/s max: 150.2 H/s

  * VERSIONS:     XMRig/2.4.4 libuv/1.18.0 gcc/7.3.0
  * HUGE PAGES:   available, enabled
  * CPU:          Intel(R) Xeon(R) CPU           E5405  @ 2.00GHz (1) x64 -AES-NI
  * CPU L2/L3:    24.0 MB/0.0 MB
  * THREADS:      8, cryptonight-lite, av=4, donate=5%, affinity=0xF

**Comment by sergneo** [comment]
lisergey, he also said that only with av=3 works
have only E5405 4 core 4 thread
we test the algorithm cryptonight and not aeon . different speed readings

**Comment by Foudge** [comment]
_av_ is algorithm variation :
0 = auto selection (check AES-NI CPU support and typically choose 1 or 3 mode)
1 = AES (need CPU with AES-NI instructions)
2 = AES double hash (lower power mode)
3 = soft AES (don't use AES-NI instructions, for "old" CPU)
4 = soft AES double hash (lower power mode)

I modified soft-AES code, so mode av=3 and av=4 are concerned.
I just check Cryptonight-lite (for AEON) and... it is just a variation of Cryptonight algo and use the same code. Contrary to my pull request title, the 2 algo are concerned, my fault.

But your configuration lisergey seems strange : 8 thread on a quadcore CPU ? But 24Mo of L2, maybe 2 CPU ? And your affinity allow only 4 cores usage. Generally, number of threads <= total physical cores.
With original XMRig, you don't have best perf with av=3 ? Why this affinity ?

**Comment by lisergey** [comment]
dear @Foudge, you're right, that's my mistake.
I was experimenting and probably left config unreversed.
I'll retest with 4 threads, that's of course optimal for this old E5405

**Comment by Foudge** [comment]
And in my opinion, best results with _av=3_

**Comment by lisergey** [comment]
on that old E5405, same config, 4 threads

XMRig/2.4.3 libuv/1.18.0 clang/4.0.0  (from ports, no patch)
speed 2.5s/60s/15m 153.9 153.7 153.6 H/s max: 154.0 H/s

Foudge-clang
speed 2.5s/60s/15m 153.7 153.1 151.9 H/s max: 153.7 H/s

Foudge-gcc7.3
speed 2.5s/60s/15m 146.4 146.0 146.1 H/s max: 146.7 H/s

**Comment by lisergey** [comment]
* VERSIONS:     XMRig/2.4.3 libuv/1.19.1 clang/4.0.0
 * HUGE PAGES:   available, enabled
 * CPU:          Intel(R) Xeon(R) CPU           X3430  @ 2.40GHz (1) x64 -AES-NI
 * CPU L2/L3:    1.0 MB/8.0 MB
 * THREADS:      4, cryptonight-lite, av=4, donate=5%, affinity=0xF
speed 2.5s/60s/15m 170.6 170.2 n/a H/s max: 170.8 H/s

Foudge-clang
speed 2.5s/60s/15m 168.6 168.9 168.9 H/s max: 169.6 H/s

Foudge-gcc7.3
speed 2.5s/60s/15m 162.2 162.1 162.2 H/s max: 162.8 H/s

**Comment by lisergey** [comment]
@Foudge and @sergneo, do you think of necessity to test with av=3 and algo=cryptonight?

**Comment by Foudge** [comment]
Thank you for your tests. So... no perf increase with cryptonight-lite. Or it's OS/compiler environnement dependent.
You have compiled your own XMRig 2.4.3 with Clang on each machine ?

**Comment by lisergey** [comment]
> compiled your own XMRig 2.4.3 with Clang on each machine
yes, from ports

xmrig-Foudge-clang was compiled on E5405, while xmrig-Foudge-gcc7.3 on Pentium(R) CPU 2020M @ 2.40GHz (1) x64 -AES-NI, because of gcc7.3 availability, then both were copied to X3430.
Does compiling on the same machine influence perf? Why, if OS and compiler are the same?

**Comment by Foudge** [comment]
If source, OS and compiler are the same and at the same version, binary result would be the same.

**Comment by lisergey** [comment]
@Foudge, I've read some years ago a notice from FreeBSD team, explaining why they switch from GCC to Clang, even with such overhead. So, this perf boost pretty much might be OS+compiler specific.
I understand that's not easy to code for every OS/compiler, and thank you for your effort! 
I enjoyed the experiment.

**Comment by sergneo** [comment]
I already changed all miners with the new code, the developer XMrig-cpu will change your code? Performance is actually higher.

**Comment by Foudge** [comment]
@xmrig has accepted my pull request, so this MSVC-only modification will probably be integrated in the next version.
But the improved version wich is compatible with all compilers and perf increase observed with MSVC&GCC (but strangely not Clang), is still on my fork repository. What does @xmrig think ?

For information, I am rewriting completely soft-aes code, there is still potential for gain !

**Comment by sergneo** [comment]
it's just great ! So keep

**Comment by jovan2009** [comment]
Hi, could somebody provide a Windows x64 build, please? I have a core 2 duo mobile cpu and with current xmrig msvc build I'm getting about 22,5 H/s on average and I would like to try @Foudge version. Unfortunately I have no experience in building apps from source.

**Comment by sergneo** [comment]
Here you go x64 GCC 7.3.0
[xmrig.zip](https://github.com/xmrig/xmrig/files/1691646/xmrig.zip)

**Comment by Foudge** [comment]
I mage a package containing few binaries, including my experimental rewrited version :)
https://github.com/Foudge/xmrig/releases/download/F2/xmrig_Foudge.zip

Can you test them all ? I frefer feedback on my ["up to 20%" commit](https://github.com/Foudge/xmrig/commit/9a28ad590ca6137bf5e19ba477e3f379527bbd73), here is the first (and obsolète) modification code.

**Comment by jovan2009** [comment]
Many thanks @sergneo  & @Foudge !
I let sergneo's build run for about an hour and it's somewhat a mixed bag. The peak h/s increased from about 23.3 to about 27-28. But the average decreased to 19, now it makes a share in 23 s at 500 diff, before was 22. Maybe a msvc build would do better.
I will try @Foudge files later in the day in a few hours when I will have the time.
I wonder if there could be way to set L2/L3 cache manually, because xmrig fails to detect my cpu's info corectly. It says Intel Core2 Duo T5800 4.0 MB / 0.0 MB. Cpu-z says Intel Mobile Core 2 Duo T5800 L1D 2x32 KB, L1I 2x32KB and L2 2048 KB, there is no L3. I will open an issue about this I think.

**Comment by sergneo** [comment]
xmrig_GCC730_exp the best speed possible to look at the source code of this version?

**Comment by Foudge** [comment]
@jovan2009  If you don't want to test all of them, forget F1 version (it's obsolète), test only F2 and Exp compiled by GCC.

@sergneo On my computer, xmrig_GCC730_exp is the faster version too! Not pushed the code, I am currently working on it : I abandoned SSE2 instructions and used 32bit instructions only. But I think we can have more performance again...

**Comment by jovan2009** [comment]
I already tested F1 msvc LOL. For about 15 min. 23.01 average, 24.82 peak, average time per share 20 sec. Now it is running msvc exp and already is peaking at 30.49, avg 60 sec 24.62, avg time per share 19.

**Comment by sergneo** [comment]
That's just great, now my Xeon E5440 speed was 108 H/s, this is incredible, fly to the moon :)

**Comment by jovan2009** [comment]
Indeed GCC EXP is great. I run it for about 10 minutes, peak 33.04, avg 60 sec 26.62, avg time per share 16.

**Comment by Foudge** [comment]
I will see your inccorect L2 cache detection ;) I have the same with my C2Q.

Can you publish a resumer of your results here?
https://github.com/Foudge/xmrig/commit/9a28ad590ca6137bf5e19ba477e3f379527bbd73

**Comment by jovan2009** [comment]
I will but right now I really have to leave home, I will test later trying to be as fair as possible with every version and give it time for meaningful averages, plus a reboot before every run. But there are really great improvements so far, many thanks for your work @Foudge !

**Comment by xmrig** [comment]
@Foudge Currently I busy and can't verify/merge changes, anyway you in right direction SSE2 for non AES CPUs is bad. Actuality for HW AES it bad too, but here no choice, it required for AES instructions.
Also take look to old/original code from https://github.com/lucasjones/cpuminer-multi/blob/master/cryptonight.c it's complete SSE2 free.

@jovan2009 Wrong cache size is known issue, but for manual configuration it doesn't matter.
Thank you.

**Comment by Foudge** [comment]
Thank you @rmrig, I just took a look. The basic XOR function (named "round" in cpuminer-multi) is is practically the same.
I had already benchmarked several miners on my non-AES CPU : cpuminer multi and cpuminer opt (seems to share same code) were the fastest. But I can say it : xmrig will be faster on our Core 2 processor.

@jovan2009 I have a [fix for the L2 cache size](https://github.com/Foudge/xmrig/commit/037abd703720cc52f228c99d1e0e205ce48abd85). All Intel Core with shared L2 cache (C2D and C2Q for example) are touched by this bug.
If ok I will do a pull request here.

**Comment by sergneo** [comment]
Yes I tested all my CPU fixed code, E8500 Q9400 E5440 now properly displays the size of L2 cache

**Comment by jovan2009** [comment]
@xmrig I see, thank you for your response

@Foudge here are my benchmark results,  posted also [here](https://github.com/Foudge/xmrig/commit/9a28ad590ca6137bf5e19ba477e3f379527bbd73)

Intel(R) Core(TM)2 Duo (Mobile) CPU T5800 @ 2.00GHz
av=3, threads=2, no cpu affinity, 15 min. averages:

GCC
original xmrig: 18.89 H/s avg, highest 22.51 (baseline)
xmrig_GCC730_exp: 24.88 H/s avg, highest 33.71 (+31.7%)
xmrig_GCC730_F2: 20.54 H/s avg, highest 28.04 (+8.73%)

MSVC
original xmrig: 19.61 H/s avg, highest 23.07 (+3.8%)
xmrig_MSVC2017_exp: 22.96 H/s avg, highest 30.81 (+21.54%)
xmrig_MSVC2017_F2: 21.6 H/s avg, highest 28.2 (+14.34%)

**Comment by lisergey** [comment]
I've just tested new release, supposedly with your improvements, @Foudge.

XMRig/2.4.5 libuv/1.19.1 clang/3.4.1
CPU: Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz (1) x64 -AES-NI
CPU L2/L3: 0.5 MB/4.0 MB

+4-5 h/s, 6%.

Great job! Thank you!!

**Comment by Foudge** [comment]
@lisergey Thank you for your message.
I see you have a Core i3 (AES-NI are present but disabled, thx Intel) and I never had feedback with this CPU.
Can you test [this version](https://github.com/Foudge/xmrig/releases/tag/F3)? With Intel Core 2 processor, we can have +30 to +50% performance increase! Only test GCC and MSVC version, not Win32. Thx
