### PR TITLE
GhostRider algorithm (Raptoreum) support

### PR DESCRIPTION
**Pull request by SChernykh**
Command line to test:
```
xmrig -a gr -o raptoreumemporium.com:3008 -u WALLET_ADDRESS
```
While individual algorithm implementations are a bit unoptimized, XMRig achieves higher hashrates by employing better auto-config and more fine-grained thread scheduling: it can calculate a single batch of hashes using 2 threads for parts that don't require much cache. For example, on a typical Intel CPU (2 MB cache per core) it will use 1 thread per core for cn/fast, and 2 threads per core for other Cryptonight variants while calculating the same batch of hashes, always achieving more than 50% CPU load.

Performance comparison with cpuminer-gr-avx2 (harmonic mean hashrates over all algo combinations):
CPU|cpuminer-gr-avx2 (tuned), h/s|xmrig, h/s|Speedup
-|-|-|-
AMD Ryzen 7 4700U|632.6|741.8|+17.2%
Intel Core i7-2600|496.4|533.6|+7.5%
AMD Ryzen 7 3700X @ 4.1 GHz|2453.0|2430.7|-0.9%
AMD Ryzen 5 5600X @ 4.65 GHz|2112.6|2188.8|+3.6%

Detailed results: https://imgur.com/a/TK1CwT0

XMRig doesn't require tuning for GhostRider, auto-config works well enough on most CPUs.

GhostRider requires HWLOC for optimal performance, non-HWLOC builds can't run proper auto-config.

**Windows users: MSVC compiled binary is a bit faster!**

### CODE REVIEW

**Comment by Titaniumtown** [comment]
When compiling with clang 13.0 on Arch Linux, I get the following error:
```
[ 12%] Linking C static library libxmrig-asm.a
[ 12%] Built target xmrig-asm
In file included from /home/simon/xmrig-gh3/src/crypto/ghostrider/ghostrider.cpp:20:
/home/simon/xmrig-gh3/src/crypto/ghostrider/./ghostrider.h:43:37: error: unknown type name 'size_t'; did you mean 'std::size_t'?
void hash_octa(const uint8_t* data, size_t size, uint8_t* output, cryptonight_ctx** ctx, HelperThread* helper);
                                    ^~~~~~
                                    std::size_t
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++config.h:280:26: note: 'std::size_t' declared here
  typedef __SIZE_TYPE__         size_t;
                                ^
```

**Comment by breezey-au** [comment]
i'm getting this error when trying to build on clang 13.0 on arch
```[ 10%] Built target argon2
/home/geo/crypto/xmrig-rtm/src/crypto/ghostrider/ghostrider.cpp: In member function ‘void xmrig::ghostrider::HelperThread::wait() const’:
/home/geo/crypto/xmrig-rtm/src/crypto/ghostrider/ghostrider.cpp:227:13: error: ‘_mm_pause’ was not declared in this scope
  227 |             _mm_pause();
      |             ^~~~~~~~~
make[2]: *** [src/crypto/ghostrider/CMakeFiles/ghostrider.dir/build.make:300: src/crypto/ghostrider/CMakeFiles/ghostrider.dir/ghostrider.cpp.o] Error 1```

**Comment by MrSMiTHex** [comment]
Would ever xmrig catch up the JCE cpuminer on cn-turtle algos? Seems it still doesn't utilize all available ryzen cache (L1+L2+L3).

**Comment by digitalspaceport** [comment]
./xmrig -a gr -o stratum+tcps://us.flockpool.com:5555 -u XXX.RPI4 -p x

[2021-11-24 04:59:16.227] unable to open "/root/xmrig/build/config.json".
[2021-11-24 04:59:16.228] unable to open "/root/.xmrig.json".
[2021-11-24 04:59:16.228] unable to open "/root/.config/xmrig.json".
[2021-11-24 04:59:16.228] no valid configuration found, try https://xmrig.com/wizard

**Comment by SChernykh** [comment]
> ./xmrig -a gr -o stratum+tcps://us.flockpool.com:5555 -u XXX.RPI4 -p x
> 
> [2021-11-24 04:59:16.227] unable to open "/root/xmrig/build/config.json". [2021-11-24 04:59:16.228] unable to open "/root/.xmrig.json". [2021-11-24 04:59:16.228] unable to open "/root/.config/xmrig.json". [2021-11-24 04:59:16.228] no valid configuration found, try https://xmrig.com/wizard

Remove `stratum+tcps://` and add `--tls` to the command line
```
./xmrig -a gr -o us.flockpool.com:5555 --tls -u XXX.RPI4 -p x
```

**Comment by Titaniumtown** [comment]
> > ./xmrig -a gr -o stratum+tcps://us.flockpool.com:5555 -u XXX.RPI4 -p x
> > [2021-11-24 04:59:16.227] unable to open "/root/xmrig/build/config.json". [2021-11-24 04:59:16.228] unable to open "/root/.xmrig.json". [2021-11-24 04:59:16.228] unable to open "/root/.config/xmrig.json". [2021-11-24 04:59:16.228] no valid configuration found, try https://xmrig.com/wizard
> 
> Remove `stratum+tcps://` and add `--tls` to the command line
> 
> ```
> ./xmrig -a gr -o us.flockpool.com:5555 --tls -u XXX.RPI4 -p x
> ```

Don't use flockpool

**Comment by Lonnegan** [comment]
How can I start the benchmark for RTM?

**Comment by younicoin** [comment]
xmrig 6.16 is not built cause of ghostrider on Devuan Linux

$ cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8
..
-- Build files have been written to: /home/y/disk-evo-500/crypto/miners/xmrig/build


$ make
[  3%] Building CXX object src/crypto/ghostrider/CMakeFiles/ghostrider.dir/ghostrider.cpp.o
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp: In function ‘xmrig::ghostrider::HelperThread* xmrig::ghostrider::create_helper_thread(int64_t, const std::vector<long int>&)’:
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:488:26: error: ‘HWLOC_OBJ_L3CACHE’ was not declared in this scope
         findByType(root, HWLOC_OBJ_L3CACHE, [cpu_index, &is8MB](hwloc_obj_t obj) {
                          ^~~~~~~~~~~~~~~~~
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:488:26: note: suggested alternative: ‘HWLOC_OBJ_CACHE’
         findByType(root, HWLOC_OBJ_L3CACHE, [cpu_index, &is8MB](hwloc_obj_t obj) {
                          ^~~~~~~~~~~~~~~~~
                          HWLOC_OBJ_CACHE
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:512:48: error: ‘HWLOC_OBJ_L1CACHE’ was not declared in this scope
         for (auto obj_type : { HWLOC_OBJ_CORE, HWLOC_OBJ_L1CACHE, HWLOC_OBJ_L2CACHE, HWLOC_OBJ_L3CACHE }) {
                                                ^~~~~~~~~~~~~~~~~
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:512:48: note: suggested alternative: ‘HWLOC_OBJ_CACHE’
         for (auto obj_type : { HWLOC_OBJ_CORE, HWLOC_OBJ_L1CACHE, HWLOC_OBJ_L2CACHE, HWLOC_OBJ_L3CACHE }) {
                                                ^~~~~~~~~~~~~~~~~
                                                HWLOC_OBJ_CACHE
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:512:67: error: ‘HWLOC_OBJ_L2CACHE’ was not declared in this scope
         for (auto obj_type : { HWLOC_OBJ_CORE, HWLOC_OBJ_L1CACHE, HWLOC_OBJ_L2CACHE, HWLOC_OBJ_L3CACHE }) {
                                                                   ^~~~~~~~~~~~~~~~~
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:512:67: note: suggested alternative: ‘HWLOC_OBJ_CACHE’
         for (auto obj_type : { HWLOC_OBJ_CORE, HWLOC_OBJ_L1CACHE, HWLOC_OBJ_L2CACHE, HWLOC_OBJ_L3CACHE }) {
                                                                   ^~~~~~~~~~~~~~~~~
                                                                   HWLOC_OBJ_CACHE
/home/user/xmrig/src/crypto/ghostrider/ghostrider.cpp:512:104: error: unable to deduce ‘std::initializer_list<_Tp>&&’ from ‘{HWLOC_OBJ_CORE, <expression error>, <expression error>, HWLOC_OBJ_L3CACHE}’
         for (auto obj_type : { HWLOC_OBJ_CORE, HWLOC_OBJ_L1CACHE, HWLOC_OBJ_L2CACHE, HWLOC_OBJ_L3CACHE }) {
                                                                                                        ^
make[2]: *** [src/crypto/ghostrider/CMakeFiles/ghostrider.dir/build.make:271: src/crypto/ghostrider/CMakeFiles/ghostrider.dir/ghostrider.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:482: src/crypto/ghostrider/CMakeFiles/ghostrider.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

uname -a
Linux devuan 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**Comment by Titaniumtown** [comment]
Why are you using gcc 8?

**Comment by younicoin** [comment]
1. I choosed it because i can get payment after half a day 1 Rtm, and this is the largest pool. I will mine 2 weeks on the second pool rplant .xyz
2. Yes i can do it, but the reason is not config but the address. I tried to create config, but the error remains when i placed such address stratum+tcps to config
3. I use devuan, and there are gcc of 8 and 7 version, and may be 9, 10

**Comment by Titaniumtown** [comment]
lol

**Comment by khansaad1275** [comment]
> > ./xmrig -a gr -o stratum+tcps://us.flockpool.com:5555 -u XXX.RPI4 -p x
> > [2021-11-24 04:59:16.227] unable to open "/root/xmrig/build/config.json". [2021-11-24 04:59:16.228] unable to open "/root/.xmrig.json". [2021-11-24 04:59:16.228] unable to open "/root/.config/xmrig.json". [2021-11-24 04:59:16.228] no valid configuration found, try https://xmrig.com/wizard
> 
> Remove `stratum+tcps://` and add `--tls` to the command line
> 
> ```
> ./xmrig -a gr -o us.flockpool.com:5555 --tls -u XXX.RPI4 -p x
> ```

I am having the same issue, what should i do, i have no clue.

**Comment by SChernykh** [comment]
@khansaad1275 change `-a` to `-o`
