### PR TITLE
Fix build with OpenSSL 4.0.0

### PR DESCRIPTION
**Pull request by bkuhls**
```
src/base/net/tls/TlsGen.cpp: In member function 'bool
 xmrig::TlsGen::generate_x509(const char*)':
src/base/net/tls/TlsGen.cpp:118:32: error: invalid conversion from
 'const X509_name_st*' to 'X509_NAME*' {aka 'X509_name_st*'}
 [-fpermissive]
  118 |     X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
      |                                ^~~~
      |                                |
      |                                const X509_name_st*
```

https://github.com/openssl/openssl/issues/29117

### CODE REVIEW

**Review by SChernykh — APPROVED** [review]

**Comment by loqs** [comment]
@bkuhls instead of casting away the const have you considered using `X509_NAME_new` to create a `X509_NAME *name` without a const, use `X509_set_subject_name` before `X509_set_issuer_name` to populate it and `X509_NAME_free` afterwards to free the created name? This is the approach used in https://github.com/znc/znc/commit/94bcf919e1163564e637df8d437585bc7b55e7aa and avoids undefined behavior.

**Comment by SChernykh** [comment]
The better fix (compared to what znc did) would be
```
auto name = X509_NAME_dup(X509_get_subject_name(cert));
X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
X509_set_issuer_name(m_x509, name);
X509_NAME_free(name);
```

**Review by SChernykh — CHANGES_REQUESTED** [review]
The better fix:
```
auto name = X509_NAME_dup(X509_get_subject_name(cert));
X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
X509_set_issuer_name(m_x509, name);
X509_NAME_free(name);
```

**Comment by loqs** [comment]
@SChernykh 
```patch
--- a/src/base/net/tls/TlsGen.cpp
+++ b/src/base/net/tls/TlsGen.cpp
@@ -114,10 +114,11 @@ bool xmrig::TlsGen::generate_x509(const char *commonName)
     X509_gmtime_adj(X509_get_notBefore(m_x509), 0);
     X509_gmtime_adj(X509_get_notAfter(m_x509), 315360000L);
 
-    auto name = X509_get_subject_name(m_x509);
+    auto name = X509_NAME_dup(X509_get_subject_name(cert));
     X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
 
     X509_set_issuer_name(m_x509, name);
+    X509_NAME_free(name);
 
     return X509_sign(m_x509, m_pkey, EVP_sha256());
 }
```
Produces:
```
/build/xmrig/src/xmrig/src/base/net/tls/TlsGen.cpp: In member function ‘bool xmrig::TlsGen::generate_x509(const char*)’:
/build/xmrig/src/xmrig/src/base/net/tls/TlsGen.cpp:117:53: error: invalid use of non-static member function ‘const xmrig::String& xmrig::TlsGen::cert() const’
  117 |     auto name = X509_NAME_dup(X509_get_subject_name(cert));
      |                                                     ^~~~
In file included from /build/xmrig/src/xmrig/src/base/net/tls/TlsGen.cpp:19:
/build/xmrig/src/xmrig/src/base/net/tls/TlsGen.h:42:26: note: declared here
   42 |     inline const String &cert() const       { return m_cert; }
      |                          ^~~~
make[2]: *** [CMakeFiles/xmrig.dir/build.make:3327: CMakeFiles/xmrig.dir/src/base/net/tls/TlsGen.cpp.o] Error 1
```

**Comment by loqs** [comment]
Did you mean:
```patch
--- a/src/base/net/tls/TlsGen.cpp
+++ b/src/base/net/tls/TlsGen.cpp
@@ -114,10 +114,11 @@ bool xmrig::TlsGen::generate_x509(const char *commonName)
     X509_gmtime_adj(X509_get_notBefore(m_x509), 0);
     X509_gmtime_adj(X509_get_notAfter(m_x509), 315360000L);
 
-    auto name = X509_get_subject_name(m_x509);
+    auto name = X509_NAME_dup(X509_get_subject_name(m_x509));
     X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
 
     X509_set_issuer_name(m_x509, name);
+    X509_NAME_free(name);
 
     return X509_sign(m_x509, m_pkey, EVP_sha256());
 }
```

**Comment by SChernykh** [comment]
Yes, it's `m_x509` there. In any case, `X509_NAME_dup/X509_NAME_free` is a proper solution here.

File: src/base/net/tls/TlsGen.cpp [hunk 1]
```diff
@@ -115,7 +115,7 @@ bool xmrig::TlsGen::generate_x509(const char *commonName)
     X509_gmtime_adj(X509_get_notAfter(m_x509), 315360000L);
 
     auto name = X509_get_subject_name(m_x509);
-    X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
+    X509_NAME_add_entry_by_txt((X509_NAME *) name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);
 
     X509_set_issuer_name(m_x509, name);
```
Comment (rroessler) [inline src/base/net/tls/TlsGen.cpp:121]: The recommended fix is to allocate a _new_ `X509_NAME` then to assign it to both the subject and issuer of the certificate (since duplication does not use the original subject name):

```cpp
auto name = X509_NAME_new();
X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, reinterpret_cast<const uint8_t *>(commonName), -1, -1, 0);

X509_set_subject_name(m_x509, name);
X509_set_issuer_name(m_x509, name);
X509_NAME_free(name);
```

**Review by rroessler — CHANGES_REQUESTED** [review]
